---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: sample-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - name: pods-sample-deployment
        image: tntaksreg.azurecr.io/sample:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
    name: sample-service
    namespace: dev
spec:
  selector:
    app: sample-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: sample-service
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
spec:
  maxReplicas: 2 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
