---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: uat
spec:
  selector:
    matchLabels:
      app: sample-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - name: pods-sample-deployment
        image: 056121157689.dkr.ecr.ap-south-1.amazonaws.com/gudexams/sample:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: sample-service
    namespace: uat
spec:
  selector:
    app: sample-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80

